[project]
name = "lexi-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "graphviz>=0.21",
    "langchain-cohere==0.3.5",
    "cohere==5.11.0",
    "streamlit>=1.47.0",
]
